version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
    networks:
      - proxy

  web:
    image: nginx:latest
    container_name: espoch_web
    restart: always
    ports:
      - "8089:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    environment:
      VIRTUAL_HOST: 192.168.34.86
      VIRTUAL_PORT: 80
    networks:
      - proxy

networks:
  proxy:
    external: true